<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis

/**
 * Product additional attributes template
 *
 * @var $block \Magento\Catalog\Block\Product\View\Attributes
 */
?>
<?php
    $_helper = $this->helper(Magento\Catalog\Helper\Output::class);
    $_product = $block->getProduct();
?>
<?php if ($_additional = $block->getAdditionalData()) :?>
    <div class="additional-attributes-wrapper table-wrapper">
<!--        <table class="data table additional-attributes" id="product-attribute-specs-table">-->
<!--            <caption class="table-caption">--><?php
        //= $block->escapeHtml(__('More Information'))
        ?><!--</caption>-->
<!--            <tbody>-->
        <ul class="attribute-list">
            <?php
            $attributeCodes = [
                'dimensions' => false,
                'color' => false,
                'material' => false,
            ];
            $allAttributes = [];
            $attributeCount = 0;
            $additionalAttributeCount = 0;
            foreach ($_additional as $_data) :
                $attributeCode = $_data['code'];
                if($attributeCode == 'dimensions' || $attributeCode == 'color' || $attributeCode == 'material') :
                    $attributeCodes[$attributeCode] = true;
                    $key = 'basic-' . $attributeCode;
                    $attributeCount++;
                else:
                    $key = 'additional-' . ++$additionalAttributeCount;
                endif;
                $allAttributes [$key] = '<li class="attribute-label"><span><strong>' . $block->escapeHtml($_data['label']) . ':</strong> ' . $_helper->productAttribute($_product, $_data['value'], $_data['code']) . '</span></li>';
            endforeach;
            foreach($attributeCodes as $attributeCode => $status):
                if($status):
                    echo $allAttributes['basic-' . $attributeCode];
                endif;
            endforeach;
            for($i = 1; $i < $additionalAttributeCount && $attributeCount  < 3; $i++, $attributeCount++):
                echo $allAttributes['additional-' . $i];
            endfor;
            ?>
        </ul>
<!--            </tbody>-->
<!--        </table>-->

<!--        $allAttributes [$key] = '<tr>-->
<!--            <th class="col label" scope="row">' . $block->escapeHtml($_data['label']) . '</th>-->
<!--            <td class="col data" data-th="' . $block->escapeHtmlAttr($_data['label']) . '">-->
<!--                ' . $_helper->productAttribute($_product, $_data['value'], $_data['code']) . '</td>-->
<!--        </tr>';-->
        <?= $block->getChildHtml('', true) ?>
    </div>
<?php endif;?>
